export enum RouterPathName {
    Home = '/',
    AboutUs = '/about-us',
    ContactUs = '/contact',
    HowItWorks = '/howWork',
    Courses = '/courses',
    NotFound = '/notFound',
    ThankYou = '/thankyou',
    NoPayment = '/noPayment',
    Contact = '/contact',
    Login = '/login',
    UnprotectedLogin = '/login-unprotected',
    Register = '/register',
    CompleteAccountSetup = '/completeAccountSetup',
    Teacher = '/teacher/:teacherName',
    Teachers = '/teacher',
    Classes = '/classesView',
    Blogs = '/blogs',
    Profile = '/profile'
}
